use_frameworks!

target 'PoporNetRecord_Example' do
  pod 'PoporNetRecord', :path => '../'
  
  # 忽略pod第三方库文件警告
  inhibit_all_warnings!
  
  # 推荐继续使用 传统的 pod
  #  source 'https://github.com/CocoaPods/Specs.git'
  #source 'https://cdn.cocoapods.org/'
  
  pod 'PoporAFN', '1.05'  #,:path => '../../PoporAFN'
  
  target 'PoporNetRecord_Tests' do
    inherit! :search_paths
    
    # 忽略pod第三方库文件警告
    inhibit_all_warnings!
    
    
  end
end
