use_frameworks!

target 'PoporNetRecord_Example' do
  pod 'PoporNetRecord', :path => '../'
  
  # 忽略pod第三方库文件警告
  inhibit_all_warnings!
  
  target 'PoporNetRecord_Tests' do
    inherit! :search_paths
    
    # 忽略pod第三方库文件警告
    inhibit_all_warnings!
    
    
  end
end
