use_frameworks!

# 解决xcode10对版本号警告的问题. 作者：Tioks0 链接：https://juejin.im/post/5ba22293e51d450e46282d68
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      if config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'].to_f < 9.0
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '9.0'
      end
    end
  end
end


target 'PoporNetRecord_Example' do
  pod 'PoporNetRecord', :path => '../'
  
  # 忽略pod第三方库文件警告
  inhibit_all_warnings!
  
  # 推荐继续使用 传统的 pod
  #  source 'https://github.com/CocoaPods/Specs.git'
  #source 'https://cdn.cocoapods.org/'
  
  pod 'PoporAFN', '1.07'  #,:path => '../../PoporAFN'
  #pod 'PoporAFN', :path => '../../PoporAFN'
  
  target 'PoporNetRecord_Tests' do
    inherit! :search_paths
    
    # 忽略pod第三方库文件警告
    inhibit_all_warnings!
    
    
  end
end
